config/routes.rb
PurpleConfiguration::Application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  namespace :api, :defaults => {:format => :json} do
      get 'configuration', to: 'phone_configurations#user_config' 
      post 'user_load', to: 'insert_users#user_insert'
  end

  root 'home#index'
  
  get '/template/get_template', to: 'template#get_template'
  get 'phone_configuration', to: 'phone_configurations#ajax', as: 'phone_config'

  resources :phone_configurations

  resources :studies do
    resources :robo_users
  end

  

end

app/models/phone_configuration.rb
class PhoneConfiguration < ActiveRecord::Base
    has_many :studies
    has_many :robo_users

    validates :json, :config_name, presence: true
end

app/models/robo_user.rb
class RoboUser < ActiveRecord::Base
    belongs_to :study
    belongs_to :phone_configuration

    validates :username, presence: true
end

app/models/study.rb
class Study < ActiveRecord::Base
    has_many :robo_users
    belongs_to :phone_configuration

    validates :study_name, presence: true
end

app/models/template.rb
class Template < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/insert_users_controller.rb
class API::InsertUsersController < ApplicationController
skip_before_filter :verify_authenticity_token
    def user_insert
        
        if params[:study_name]
            @study = Study.where(:study_name => params[:study_name]).first_or_initialize
            @study.update_attributes(:study_name => params[:study_name])
          
            if params[:pr_id]
                robo_username = params[:pr_id]
                user = RoboUser.where(:username => robo_username).first_or_initialize
                user.update_attributes(:study_id => @study.id)
            end
            render :json => { :success => "updated study and robo user successfully" }
        else
            render :json => { :errors => "invalid data" }
        end
     
    end
end

app/controllers/api/phone_configurations_controller.rb
require 'json'

class API::PhoneConfigurationsController < ApplicationController

    def user_config
        user = RoboUser.where(:username => params[:user_id]).first
        if user.phone_configuration
            @phone_configuration = user.phone_configuration

            render :json => PurpleRobot.config_from_hash(JSON.parse(@phone_configuration.json)) 
        else
            render :json => { :errors => "user configuration not found" }
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   before_filter :authenticate_user!
 
    def index
        @users = RoboUser.all
        @configurations = PhoneConfiguration.all
        @studies = Study.all
    end
        
end

app/controllers/phone_configurations_controller.rb
class PhoneConfigurationsController < ApplicationController

   before_filter :authenticate_user!

    def index
        @configs = PhoneConfiguration.all
        @studies = Study.all
    end

    def ajax

        if params[:id]
            @phone_config = PhoneConfiguration.where(:id => params[:id]).first
        
        else
            robo_user = RoboUser.where(:id => params[:user_id]).first
            @phone_config = robo_user.phone_configuration 
        end

       render :json => (@phone_config || {}).to_json

    end

    def create
        @config = PhoneConfiguration.where(:id => params[:phone_configuration][:id]).first_or_initialize
        @config.update_attributes(config_params)

        if params[:phone_configuration][:robo_user_id]
            user = RoboUser.where(:id => params[:phone_configuration][:robo_user_id]).first
            user.phone_configuration = @config
            user.save
        end

        if params[:phone_configuration][:study_id]
            study = Study.where(:id => params[:phone_configuration][:study_id]).first
            study.phone_configuration = @config
            study.save
            study.robo_users.each do |robo_user|
                robo_user.phone_configuration = @config
                robo_user.save
            end
        end
        respond_to do |format|
            format.json { head :ok }
        end
    end

    def destroy
        @config = PhoneConfiguration.where(:id => params[:id]).first
        @config.destroy
        redirect_to :action => 'index'
    end
    
    private

    def config_params
        params.require(:phone_configuration).permit(:config_name, :json, :id)
    end
end

app/controllers/robo_users_controller.rb
class RoboUsersController < ApplicationController
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
end

app/controllers/template_controller.rb
class TemplateController < ApplicationController
    
    def get_template
        @template = Template.first
        render json: @template.json
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phone_configurations_helper.rb
module PhoneConfigurationsHelper
end

app/helpers/robo_users_helper.rb
module RoboUsersHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/home/index.html.erb
    <div class="row">
        <div class="span3 well">
            <h1>Participants</h1>
            <% @studies.each do |study| %>

                <div class='study-list'>
                    <div class="study-heading foo"><%= study.study_name %></div>
                    <ul>
                    <% study.robo_users.each do |user| %>
                        <li><div class="radio"><label><input class="user-radio" type='radio' name='userRadio' value="<%=user.id%>"><%=user.username%> <strong class="pull-right"><%=user.phone_configuration.id rescue ''%></strong> </label></div></li>
                    <% end %>
                    </ul>
                </div>
            <% end %>
        </div>
        
        <div class="span8">
            <form class="form-horizontal" action="" method="post" id="configurator" >
                <fieldset>
                        <input type='hidden' value='' />
                        <h1 class="headline-index">Edit Participant Configuration</h1>
                        <div class='control-group well home-well'>
                            <label class='control-label' for='nickname'>Configuration Name</label>
                            <div class='controls'>
                                <input placeholder='Required' class='form-control pull-left' type='text' id='nickname' />
                                <div class='btn btn-small btn-inverse pull-right' id='clear-form'>Clear Form</div>
                        </div>
                    </div>
                <div class="form-toggles-index">
                        <i id="toggle-all" class="icon-plus-sign icon-2x"></i>
                        <i id="close-all" class="icon-minus-sign icon-2x"></i>
                </div>
                    <ul class="config-form" ></ul>
                </fieldset>
            </form>
        </div> 
  </div>
</div>
</body> 
<script>
$(document).ready (function(){
    $("form :input").on("keypress", function(e) {
        return e.keyCode != 13;
    });
    $('#toggle-all').on("click", function(){
        $('.collapsible').collapsible('open');
    });
    $('#close-all').on("click", function(){
        $('.collapsible').collapsible('close');
    });
    $('.form-toggles-index').hide();
    $('.foo').collapsible();
    $('.user-radio').on("click", function(e) {
        if($('.submit')){
            $('.submit').off("click");
        }
        var user = $('[type="radio"]:checked').val();
        csrf();
        $.ajax({
            url:"<%=phone_config_path%>",
            type: "GET",
            data: {user_id: user},
            success:function(response){
                $.getJSON("/template/get_template", function(data){
                    $('.form-toggles-index').show();
                    $('.config-form').html(''); 
                    $('.config-form').append(parse_recursive(data.configuration));
                    if($('.submit').length == 0){
                        $('#configurator').append("<div class='pull-right submit btn btn-large btn-warning'>Submit Configuration</div>");
                    }
                    $('.collapsible').collapsible();
                    $('.collapsible').first().collapsible('open');
                    $('#clear-form').on("click", function(){
                        getTemplate();
                        $('[type="radio"]:checked').prop('checked', false);
                    });

                console.log(response);
                    $('[type="hidden"]').val('');
                    $('#nickname').val('');
                    if(!$.isEmptyObject(response)){
                        fillForm(jQuery.parseJSON(response.json));
                        console.log(response.config_name);
                        $('#nickname').val(response.config_name);
                    }
                    $('.submit').on("click", function(e) {
                        var json_config = JSON.stringify(serializeObject($('input, select')));
                        var config_name = $('#nickname').val();
                        var user = $('[type="radio"]:checked').val();
                        csrf();
                        $.ajax({
                            url:'/phone_configurations',
                            type: "POST",
                            data: {phone_configuration: {json: json_config, config_name: config_name, robo_user_id: user}},
                            success:function(response){
                            },
                            complete:function(){
                                console.log("heyo");
                                $('#nickname').val('');
                                location.reload(true);
                            },
                            error:function (xhr, textStatus, thrownError){}
                        });
                        return true;
                    });
                });
            },
            complete:function(){},
            error:function (xhr, textStatus, thrownError){}
        });
    });
});
</script> 			

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title PurpleConfiguration
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = nav_bar :static => :top, :brand => "Purple Configurator" do
      = menu_group do
        = menu_item "Home", root_path
        = menu_item "Configurations", phone_configurations_path
      - if user_signed_in?
        = link_to 'Sign out', destroy_user_session_path, :method => :delete, :class => "btn btn-danger  pull-right"
    .container#top
      = yield
    .footer

app/views/phone_configurations/index.html.erb
<div class="row">
    <div class="span3">
        <h1>Edit Defaults</h1>
        <ul class="config-list">
        <% @configs.each do |config| %>
            <li><div class="radio default-config">
                    <label class="config" for="config-<%=config.id%>">
                        <input name="configurations" id="config-<%=config.id%>" type="radio"><%= config.config_name%> 
                        <%= link_to phone_configuration_path(:id => config.id),:confirm => "Are you sure you want to delete this configuration?", method: :delete do %>
                            <i class="icon-remove-circle delete-icon pull-right"></i>
                        <% end %>
                    </label>
                </div>
            </li>
        <% end %>
        </ul>
    </div>
    <div class="span6 config-column">
        <h1 class='headline text-center'>Default Configurer</h1>
        <form class="form-horizontal" action="" method="post" id="configurator" >
            <fieldset class="center well">
                <div class="form-toggles pull-left">
                        <i id="toggle-all" class="icon-plus-sign icon-2x"></i>
                        <i id="close-all" class="icon-minus-sign icon-2x"></i>
                </div>
                <div id='name-label' class='control-group'>
                    <label class='control-label config-label' for='nickname'>Configuration Name</label>
                    <div class="controls">
                        <input placeholder="Required" class='form-control input-medium pull-left' type='text' id='nickname' />
                        <div class='btn btn-small btn-inverse pull-right' id='clear-form'>Clear Form</div>
                    </div>
                </div>
                <input type='hidden' value='' />
            </fieldset>
            <ul class="config-form" ></ul>
        </form>
    </div> 
    <div class="span3">
        <h1>Assign Study</h1>
        <ul class="config-list">
        <% @studies.each do |study| %>
            <li><div class="radio default-config">
                    <label class="config" for="study-<%=study.id%>">
                        <input name="studies" id="study-<%=study.id%>" type="radio"><%= study.study_name%> 
                    </label>
                </div>
            </li>
        <% end %>
        </ul>
    </div>
        
</div>
<script>
$(document).ready (function(){
    $("form :input").on("keypress", function(e) {
        return e.keyCode != 13;
    });

    $('#clear-form').on("click", function(){
        getTemplate();
        $('[type="radio"]:checked').prop('checked', false);
    });

    $('#toggle-all').on("click", function(){
        $('.collapsible').collapsible('open');
    });
    $('#close-all').on("click", function(){
        $('.collapsible').collapsible('close');
    });
        
    $.getJSON("/template/get_template", function(data){
        $('#configurator').append("<div class='submit btn btn-warning pull-right'>Submit Configuration</div>");
        $('.config-form').append(parse_recursive(data.configuration));
        $('[type="hidden"]').val('');
        $('#nickname').val('');
        $('.collapsible').collapsible();
        $('.collapsible').first().collapsible('open');
        $('.submit').on("click", function(e) {
            if($('[name="studies"]:checked').length > 0){
                var study_id = $('[name="studies"]:checked').attr('id').split("-")[1];
            }
            var json_config = JSON.stringify(serializeObject($('input, select')));
            var config_name = $('#nickname').val();
            var config_id = $('[type="hidden"]').val();
            csrf();
            $.ajax({
                url:'/phone_configurations',
                type: "POST",
                data: {phone_configuration: {study_id:study_id, json: json_config, config_name: config_name}},
                success:function(response){
                },
                complete:function(){
                    console.log("heyo");
                    $('#nickname').val('');
                    location.reload();
                },
                error:function (xhr, textStatus, thrownError){}
            });
            return true;
        });
    });

    $('[name="configurations"]').on("click", function(e) {
        if($('.submit')){
            $('.submit').off("click");
        }
        var config_id = $('[name="configurations"]:checked').attr('id').split("-")[1];
        csrf();
        $.ajax({
            url:"<%=phone_config_path%>",
            type: "GET",
            data: {id: config_id},
            success:function(response){
                $.getJSON("/template/get_template", function(data){
                    console.log(response.id);
                    $('.config-form').html(''); 
                    $('.config-form').append(parse_recursive(data.configuration));
                    if($('.submit').length == 0){
                        $('#configurator').append("<div class='submit btn btn-large btn-warning'>Submit Configuration</div>");
                    }
                    $('.collapsible').collapsible();
                    $('.collapsible').first().collapsible('open');

                    $('[type="hidden"]').val('');
                    $('#nickname').val('');
                    if(!$.isEmptyObject(response)){
                        fillForm(jQuery.parseJSON(response.json));
                        console.log(response.config_name);
                        $('#nickname').val(response.config_name);
                        $('[type="hidden"]').val(response.id);
                    }
                    $('.submit').on("click", function(e) {
                        var json_config = JSON.stringify(serializeObject($('input, select')));
                        if($('[name="studies"]:checked').length > 0){
                            var study_id = $('[name="studies"]:checked').attr('id').split("-")[1];
                        }
                        var config_name = $('#nickname').val();
                        var user = $('[type="radio"]:checked').val();
                        var config_id = $('[type="hidden"]').val();
                        csrf();
                        $.ajax({
                            url:'/phone_configurations',
                            type: "POST",
                            data: {phone_configuration: {study_id: study_id, json: json_config, id: config_id, config_name: config_name}},
                            success:function(response){
                            },
                            complete:function(){
                                console.log("heyo");
                                $('#nickname').val('');
                                location.reload();
                            },
                            error:function (xhr, textStatus, thrownError){}
                        });
                        return true;
                    });
                });
            },
            complete:function(){},
            error:function (xhr, textStatus, thrownError){}
        });
    });
});
</script> 			